### ISSUE TITLE
cv_goodExample.pdf

### ISSUE THREAD

**Issue by jensharder91** [ramtinazimi/life-skills#1]
Hi @ramtinazimi ,
is it possible to upload a cv_goodExample.pdf next to the bad example? It would be very nice to compare both cv versions without going through the presentation.
The presentation is very good, but to get a quick overview a best practice version would be handy.

**Comment by ramtinazimi** [comment]
Good idea, I do it right away!

**Comment by ramtinazimi** [comment]
Done.

Ramtin Azimi


Mail:           rt.azimi@gmail.com
Mobile:       (+49) 15737864436
Website:     ramtinazimi.com <http://www.ramtinazimi.com>
